build:
    environment:
        php:
            version: 7.2

checks:
    php:
        code_rating: true

filter:
    excluded_paths:
    - config/*
    - tests/*
    - src/Generated/*
    - src/Pyz/*
